# world settings
json_dir: /../HouseExpo/json
png_dir: /../assets/png
map_id_train_set: /../assets/map_id_1.txt
map_id_eval_set: /../assets/map_id_1.txt

# [GC,LC,NC]
comm_mode: NC

# model-related hyperparam
test: False
e_render : True
load_model: False
MODEL_PATH: 'E:\Summer Research 2023\MADDPG\MADDPG\model\2023_08_08_12_02_47\model-200.pth'
batch_size: 20
n_episode: 300
max_steps: 50
episodes_before_train: 20
model_save_eps: 10
temperature: 1.0

# robots settings
robots:
  number: 2
  robotRadius: 3
  commRange: 60
  syncRange: 20
  resetRandomPose: 0
  startPose:
    x: 61
    y: 61
  w1: 0.00002
  w2: 0.001
  w3: 0.1
#  w1: 0.0002
#  w2: 0.001

  subregionSize:
    y: 20
    x: 20

# sensor settings
laser:
  range: 20
  fov: 360
  resolution: 0.1


# others
stateSize:
  x: 145
  y: 145

# frontiers
frontiers:
  number: 8

# map
map:
  y: 200
  x: 200

# color
color:
  # free: 10
  # obstacle: 100
  # uncertain: 55
  # self: 200
  # others: 150
  # fog: 255

  free: 0
  obstacle: 100
  uncertain: 50
  self: 200
  others: 150
  fog: 255

hyperparams:
  alpha1: 0.01
  alpha2: 0.01