# world settings
json_dir: /../HouseExpo/json
png_dir: /../assets/png
map_id_train_set: /../assets/map_1.txt
map_id_eval_set: /../assets/map_1.txt

# [GC,LC,NC]
comm_mode: LC

# model-related hyperparam
done_expoloration: 0.95
test: False
#test: True
e_render : False
#e_render : True
load_model: False
#load_model: True
MODEL_PATH: 'D:\2023 Summer\MADDPG\model\2023_09_07_11_20_07\model-490.pth'
#MODEL_PATH: ''
#MODEL_PATH: 'E:\Summer Research 2023\MADDPG\MADDPG\model\2023_08_17_22_31_45\lowest_step-13.pth'
batch_size: 60
n_episode: 500
max_steps: 50
episodes_before_train: 60
model_save_eps: 100
temperature: 1.0

GAMMA: 0.95
tau: 0.01
critic_lr: 0.001
actor_lr: 0.0001

# robots settings
robots:

  commRange: 200
  syncRange: 200
  number: 7
  robot1:
    color: 100
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 7
      y: 7
    laser:
      range: 10
      fov: 60
      resolution: 0.1

  robot2:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 75
      y: 75
    laser:
      range: 10
      fov: 60
      resolution: 0.1
  robot3:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 5
      y: 45
    laser:
      range: 10
      fov: 60
      resolution: 0.1
  robot4:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 75
      y: 5
    laser:
      range: 10
      fov: 60
      resolution: 0.1
  robot5:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 40
      y: 30
    laser:
      range: 10
      fov: 60
      resolution: 0.1
  robot6:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 60
      y: 30
    laser:
      range: 10
      fov: 60
      resolution: 0.1
  robot7:
    color: 150
    robotRadius: 1
    resetRandomPose: 0
    startPose:
      x: 20
      y: 30
    laser:
      range: 10
      fov: 60
      resolution: 0.1



  w1: 0.00002
  w2: 0.001
  w3: 0.1


# others
stateSize:
  x: 145
  y: 145

# frontiers
frontiers:
  number: 8

# map
map:
  y: 80
  x: 80

# color
color:
  # free: 10
  # obstacle: 100
  # uncertain: 55
  # self: 200
  # others: 150
  # fog: 255
  free: 0
  obstacle: 100
  uncertain: 50
  self: 200
  others: 150
  fog: 255
hyperparams:
  alpha1: 0.01
  alpha2: 0.01